package main

import (
	"os"
	"os/signal"
	"syscall"

	"github.com/ivpusic/golog"
)

var (
	logger    = golog.GetLogger("github.com/ivpusic/rerun")
	TEST_MODE = false
)

func main() {
	// CPrint("ERROR", aurora.RedFg, "Unable to load configuration!")
	// log.Panicf("%s: %s %s", aurora.Red("[ERROR]"), "Error while loading configuration!", err.Error())

	conf, err := loadConfiguration()
	if err != nil {
		logger.Panicf("Error while loading configuration: %s", err.Error())
	}

	// setup logger level
	if *verbose {
		logger.Level = golog.DEBUG
	} else {
		logger.Level = golog.INFO
	}

	pm := &processManager{
		conf: conf,
	}

	w := &watcher{pm: pm}

	sigs := make(chan os.Signal)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	// on ctrl+c remove build files
	go func(conf *config) {
		<-sigs

		logger.Debug("Cleaning up build files generated by rerun...")
		err := os.Remove(conf.build)
		if err != nil && !os.IsNotExist(err) {
			logger.Warnf("Unable to remove build files: %s", err.Error())
		}

		os.Exit(0)
	}(conf)

	w.start()
}
